In [35]:
import tensorflow as tf
import pandas as pd
import numpy as np
from sklearn.preprocessing import scale

In [36]:
path = './UJIIndoorLoc/trainingData2.csv'
train_df = pd.read_csv(path,header=0)
train_df

WAP001  WAP002  WAP003  WAP004  WAP005  WAP006  WAP007  WAP008  WAP009  \
0        -110    -110    -110    -110    -110    -110    -110    -110    -110   
1        -110    -110    -110    -110    -110    -110    -110    -110    -110   
2        -110    -110    -110    -110    -110    -110    -110     -97    -110   
3        -110    -110    -110    -110    -110    -110    -110    -110    -110   
4        -110    -110    -110    -110    -110    -110    -110    -110    -110   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
19932    -110    -110    -110    -110    -110    -110    -110    -110    -110   
19933    -110    -110    -110    -110    -110    -110    -110    -110    -110   
19934    -110    -110    -110    -110    -110    -110    -110    -110    -110   
19935    -110    -110    -110    -110    -110    -110    -110    -110    -110   
19936    -110    -110    -110    -110    -110    -110    -110    -110    -110   

       WAP010  ...  WAP520  LONGITUDE      LATITUDE  FLOOR  BUILDINGID  \
0        -110  ...    -110 -7541.2643  4.864921e+06      2           1   
1        -110  ...    -110 -7536.6212  4.864934e+06      2           1   
2        -110  ...    -110 -7519.1524  4.864950e+06      2           1   
3        -110  ...    -110 -7524.5704  4.864934e+06      2           1   
4        -110  ...    -110 -7632.1436  4.864982e+06      0           0   
...       ...  ...     ...        ...           ...    ...         ...   
19932    -110  ...    -110 -7485.4686  4.864875e+06      3           1   
19933    -110  ...    -110 -7390.6206  4.864836e+06      1           2   
19934    -110  ...    -110 -7516.8415  4.864889e+06      3           1   
19935    -110  ...    -110 -7537.3219  4.864896e+06      3           1   
19936    -110  ...    -110 -7536.1658  4.864898e+06      3           1   

       SPACEID  RELATIVEPOSITION  USERID  PHONEID   TIMESTAMP  
0          106                 2       2       23  1371713733  
1          106                 2       2       23  1371713691  
2          103                 2       2       23  1371714095  
3          102                 2       2       23  1371713807  
4          122                 2      11       13  1369909710  
...        ...               ...     ...      ...         ...  
19932        1                 2      18       10  1371710683  
19933      140                 2      18       10  1371710402  
19934       13                 2      18       10  1371710921  
19935      113                 2      18       10  1371711049  
19936      112                 2      18       10  1371711025  

[19937 rows x 529 columns]

In [37]:
train_ap_features = scale(np.asarray(train_df.iloc[:,:520]).astype(float),axis = 1)
train_ap_features

array([[-0.17125017, -0.17125017, -0.17125017, ..., -0.17125017,
        -0.17125017, -0.17125017],
       [-0.16059846, -0.16059846, -0.16059846, ..., -0.16059846,
        -0.16059846, -0.16059846],
       [-0.15523113, -0.15523113, -0.15523113, ..., -0.15523113,
        -0.15523113, -0.15523113],
       ...,
       [-0.1077911 , -0.1077911 , -0.1077911 , ..., -0.1077911 ,
        -0.1077911 , -0.1077911 ],
       [-0.17141826, -0.17141826, -0.17141826, ..., -0.17141826,
        -0.17141826, -0.17141826],
       [-0.17331788, -0.17331788, -0.17331788, ..., -0.17331788,
        -0.17331788, -0.17331788]])

In [38]:
train_df['REFPOINT'] = train_df.apply(lambda row: str(int(row['SPACEID'])) + str(int(row['RELATIVEPOSITION'])),
                                  axis=1)
train_df

WAP001  WAP002  WAP003  WAP004  WAP005  WAP006  WAP007  WAP008  WAP009  \
0        -110    -110    -110    -110    -110    -110    -110    -110    -110   
1        -110    -110    -110    -110    -110    -110    -110    -110    -110   
2        -110    -110    -110    -110    -110    -110    -110     -97    -110   
3        -110    -110    -110    -110    -110    -110    -110    -110    -110   
4        -110    -110    -110    -110    -110    -110    -110    -110    -110   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
19932    -110    -110    -110    -110    -110    -110    -110    -110    -110   
19933    -110    -110    -110    -110    -110    -110    -110    -110    -110   
19934    -110    -110    -110    -110    -110    -110    -110    -110    -110   
19935    -110    -110    -110    -110    -110    -110    -110    -110    -110   
19936    -110    -110    -110    -110    -110    -110    -110    -110    -110   

       WAP010  ...  LONGITUDE      LATITUDE  FLOOR  BUILDINGID  SPACEID  \
0        -110  ... -7541.2643  4.864921e+06      2           1      106   
1        -110  ... -7536.6212  4.864934e+06      2           1      106   
2        -110  ... -7519.1524  4.864950e+06      2           1      103   
3        -110  ... -7524.5704  4.864934e+06      2           1      102   
4        -110  ... -7632.1436  4.864982e+06      0           0      122   
...       ...  ...        ...           ...    ...         ...      ...   
19932    -110  ... -7485.4686  4.864875e+06      3           1        1   
19933    -110  ... -7390.6206  4.864836e+06      1           2      140   
19934    -110  ... -7516.8415  4.864889e+06      3           1       13   
19935    -110  ... -7537.3219  4.864896e+06      3           1      113   
19936    -110  ... -7536.1658  4.864898e+06      3           1      112   

       RELATIVEPOSITION  USERID  PHONEID   TIMESTAMP  REFPOINT  
0                     2       2       23  1371713733      1062  
1                     2       2       23  1371713691      1062  
2                     2       2       23  1371714095      1032  
3                     2       2       23  1371713807      1022  
4                     2      11       13  1369909710      1222  
...                 ...     ...      ...         ...       ...  
19932                 2      18       10  1371710683        12  
19933                 2      18       10  1371710402      1402  
19934                 2      18       10  1371710921       132  
19935                 2      18       10  1371711049      1132  
19936                 2      18       10  1371711025      1122  

[19937 rows x 530 columns]

In [39]:
blds = np.unique(train_df[['BUILDINGID']])
flrs = np.unique(train_df[['FLOOR']])
blds
flrs

array([0, 1, 2, 3, 4], dtype=int64)

In [40]:
for bld in blds:
    for flr in flrs:
        cond = (train_df['BUILDINGID'] == bld) & (train_df['FLOOR'] == flr)
        _, idx = np.unique(train_df.loc[cond, 'REFPOINT'], return_inverse=True)  # refer to numpy.unique manual
        train_df.loc[cond, 'REFPOINT'] = idx

In [41]:
#独热编码  ##映射Building和Floor到REFPOINT的方法
blds = np.asarray(pd.get_dummies(train_df['BUILDINGID']))#3
flrs = np.asarray(pd.get_dummies(train_df['FLOOR']))#5
rfps = np.asarray(pd.get_dummies(train_df['REFPOINT']))#110
train_labels = np.concatenate((blds, flrs, rfps), axis=1) #118
OUTPUT_DIM = train_labels.shape[1]#118

C:\Users\xfp\anaconda3\envs\tensorflow\lib\site-packages\pandas\core\algorithms.py:798: FutureWarning: In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)
  uniques = Index(uniques)


In [42]:
#len(train_ap_features) 19937
train_val_split = np.random.rand(len(train_ap_features)) < 0.9
# train_val_split ==>> array([ True,  True,  True, ...,  True,  True,  True])
x_train = train_ap_features[train_val_split]
y_train = train_labels[train_val_split]
x_val = train_ap_features[~train_val_split]
y_val = train_labels[~train_val_split]

In [43]:
#build sae encoder
from keras.layers import Dense, Dropout
from keras.models import Sequential
model = Sequential()
sae_hidden_layers= [256,128,64,128,256]
model.add(Dense(sae_hidden_layers[0],input_dim=520,activation='relu',use_bias=False))
for units in sae_hidden_layers[1:]:
    model.add(Dense(units, activation='relu', use_bias=False))
model.add(Dense(520, activation='relu', use_bias=False))
model.compile(optimizer='adam', loss='mse')
model.fit(x_train,x_train,batch_size=64,epochs=20,verbose=1)

Epoch 1/20
281/281 [==============================] - 1s 2ms/step - loss: 0.4278
Epoch 2/20
281/281 [==============================] - 1s 3ms/step - loss: 0.3125
Epoch 3/20
281/281 [==============================] - 1s 2ms/step - loss: 0.2928
Epoch 4/20
281/281 [==============================] - 1s 2ms/step - loss: 0.2842
Epoch 5/20
281/281 [==============================] - 1s 2ms/step - loss: 0.2785
Epoch 6/20
281/281 [==============================] - 1s 2ms/step - loss: 0.2749
Epoch 7/20
281/281 [==============================] - 1s 3ms/step - loss: 0.2726
Epoch 8/20
281/281 [==============================] - 1s 2ms/step - loss: 0.2709
Epoch 9/20
281/281 [==============================] - 1s 2ms/step - loss: 0.2695
Epoch 10/20
281/281 [==============================] - 1s 2ms/step - loss: 0.2685
Epoch 11/20
281/281 [==============================] - 1s 2ms/step - loss: 0.2678
Epoch 12/20
281/281 [==============================] - 1s 2ms/step - loss: 0.2671
Epoch 13/20
281/281 [====

In [44]:
num_to_remove = (len(sae_hidden_layers) + 1) // 2
for i in range(num_to_remove):
    model.pop()

In [45]:
# build and train a complete model with the trained SAE encoder and a new classifier
classifier_hidden_layers = [128,128]
model.add(Dropout(0))
for units in classifier_hidden_layers:
    model.add(Dense(units, activation='relu', use_bias=False))
    model.add(Dropout(0))
model.add(Dense(OUTPUT_DIM, activation='sigmoid', use_bias=False))  # 'sigmoid' for multi-label classification
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(x_train, y_train, validation_data=(x_val, y_val), batch_size=64, epochs=20, verbose=1)

Epoch 1/20
281/281 [==============================] - 1s 2ms/step - loss: 0.0912 - accuracy: 0.8297 - val_loss: 0.0488 - val_accuracy: 0.8310
Epoch 2/20
281/281 [==============================] - 1s 2ms/step - loss: 0.0417 - accuracy: 0.7543 - val_loss: 0.0395 - val_accuracy: 0.7217
Epoch 3/20
281/281 [==============================] - 1s 2ms/step - loss: 0.0346 - accuracy: 0.7084 - val_loss: 0.0344 - val_accuracy: 0.6711
Epoch 4/20
281/281 [==============================] - 1s 2ms/step - loss: 0.0300 - accuracy: 0.6826 - val_loss: 0.0312 - val_accuracy: 0.6513
Epoch 5/20
281/281 [==============================] - 1s 2ms/step - loss: 0.0268 - accuracy: 0.6589 - val_loss: 0.0288 - val_accuracy: 0.6776
Epoch 6/20
281/281 [==============================] - 1s 2ms/step - loss: 0.0244 - accuracy: 0.6525 - val_loss: 0.0272 - val_accuracy: 0.6660
Epoch 7/20
281/281 [==============================] - 1s 2ms/step - loss: 0.0224 - accuracy: 0.6638 - val_loss: 0.0258 - val_accuracy: 0.7166
Epoch 

In [46]:
v_path = './UJIIndoorLoc/validationData2.csv'
test_df = pd.read_csv(v_path, header=0)
# test_df['REFPOINT'] = test_df.apply(lambda row: str(int(row['SPACEID'])) + str(int(row['RELATIVEPOSITION'])),
#                                   axis=1)
# blds = np.unique(test_df[['BUILDINGID']])
# flrs = np.unique(test_df[['FLOOR']])
# for bld in blds:
#     for flr in flrs:
#         cond = (test_df['BUILDINGID'] == bld) & (test_df['FLOOR'] == flr)
#         _, idx = np.unique(test_df.loc[cond, 'REFPOINT'], return_inverse=True)  # refer to numpy.unique manual
#         test_df.loc[cond, 'REFPOINT'] = idx

In [47]:
test_AP_features = scale(np.asarray(test_df.iloc[:, 0:520]).astype(float),
                             axis=1)  # convert integer to float and scale jointly (axis=1)
x_test_utm = np.asarray(test_df['LONGITUDE'])
y_test_utm = np.asarray(test_df['LATITUDE'])
blds = np.asarray(pd.get_dummies(test_df['BUILDINGID']))
flrs = np.asarray(pd.get_dummies(test_df['FLOOR']))
# rfps = np.asarray(pd.get_dummies(test_df['REFPOINT']))
# test_labels = np.concatenate((blds, flrs, rfps), axis=1)
test_labels = np.concatenate((blds, flrs), axis=1)
test_labels.shape

(1111, 8)

In [48]:
preds = model.predict(test_AP_features, batch_size=10)
n_preds = preds.shape[0]
blds_results = (np.equal(np.argmax(test_labels[:, :3], axis=1), np.argmax(preds[:, :3], axis=1))).astype(int)
blds_results

112/112 [==============================] - 0s 563us/step


array([0, 1, 1, ..., 1, 1, 1])

In [49]:
acc_bld = blds_results.mean()
flrs_results = (np.equal(np.argmax(test_labels[:, 3:8], axis=1), np.argmax(preds[:, 3:8], axis=1))).astype(int)
acc_flr = flrs_results.mean()
acc_bf = (blds_results * flrs_results).mean()
# rfps_results = (np.equal(np.argmax(test_labels[:, 8:118], axis=1), np.argmax(preds[:, 8:118], axis=1))).astype(int)
# acc_rfp = rfps_results.mean()
# acc = (blds_results*flrs_results*rfps_results).mean()
# rfps_results
acc_bld,acc_flr,acc_bf

(0.9810981098109811, 0.8856885688568857, 0.8775877587758776)

In [50]:
# calculate positioning error when building and floor are correctly estimated
x_test_utm = np.asarray(test_df['LONGITUDE'])
y_test_utm = np.asarray(test_df['LATITUDE'])
mask = np.logical_and(blds_results, flrs_results)  # mask index array for correct location of building and floor
x_test_utm = x_test_utm[mask]
y_test_utm = y_test_utm[mask]
blds = blds[mask]
flrs = flrs[mask]
rfps = (preds[mask])[:, 8:118]
blds,flrs,blds.shape,flrs.shape

(array([[0, 0, 1],
        [0, 0, 1],
        [0, 0, 1],
        ...,
        [1, 0, 0],
        [1, 0, 0],
        [1, 0, 0]], dtype=uint8),
 array([[0, 0, 0, 0, 1],
        [0, 0, 0, 0, 1],
        [0, 0, 0, 0, 1],
        ...,
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0]], dtype=uint8),
 (975, 3),
 (975, 5))

In [51]:
n_success = len(blds)  # number of correct building and floor location
blds = np.greater_equal(blds, np.tile(np.amax(blds, axis=1).reshape(n_success, 1), (1, 3))).astype(
        int)  # set maximum column to 1 and others to 0 (row-wise)
flrs = np.greater_equal(flrs, np.tile(np.amax(flrs, axis=1).reshape(n_success, 1), (1, 5))).astype(int)
n_success,blds,flrs,blds.shape,flrs.shape

(975,
 array([[0, 0, 1],
        [0, 0, 1],
        [0, 0, 1],
        ...,
        [1, 0, 0],
        [1, 0, 0],
        [1, 0, 0]]),
 array([[0, 0, 0, 0, 1],
        [0, 0, 0, 0, 1],
        [0, 0, 0, 0, 1],
        ...,
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0]]),
 (975, 3),
 (975, 5))

In [52]:
import math
n_loc_failure = 0
sum_pos_err = 0.0
sum_pos_err_weighted = 0.0
idxs = np.argpartition(rfps, -1)[:, -1:]  # (unsorted) indexes of up to N nearest neighbors
threshold = 0 * np.amax(rfps, axis=1)
for i in range(n_success):
    xs = []
    ys = []
    ws = []
    for j in idxs[i]:
        rfp = np.zeros(110)
        rfp[j] = 1
        rows = np.where(
                (train_labels == np.concatenate((blds[i], flrs[i], rfp))).all(axis=1))  # tuple of row indexes
        if rows[0].size > 0:
            if rfps[i][j] >= threshold[i]:
                xs.append(train_df.iloc[rows[0][0], 520])  # LONGITUDE
                ys.append(train_df.iloc[rows[0][0], 521])  # LATITUDE
                ws.append(rfps[i][j])
    if len(xs) > 0:
        sum_pos_err += math.sqrt((np.mean(xs) - x_test_utm[i]) ** 2 + (np.mean(ys) - y_test_utm[i]) ** 2)
        sum_pos_err_weighted += math.sqrt(
                (np.average(xs, weights=ws) - x_test_utm[i]) ** 2 + (np.average(ys, weights=ws) - y_test_utm[i]) ** 2)
    else:
        n_loc_failure += 1
mean_pos_err = sum_pos_err / (n_success - n_loc_failure)
mean_pos_err_weighted = sum_pos_err_weighted / (n_success - n_loc_failure)
loc_failure = n_loc_failure / n_success  # rate of location estimation failure given that building and floor are correctly located
mean_pos_err,mean_pos_err_weighted,loc_failure,n_loc_failure

(12.133906478985502, 12.13390647898962, 0.006153846153846154, 6)