In [11]:
import numpy as np
import pandas as pd
from sklearn import neighbors
import random as random
from sklearn.model_selection import train_test_split
from sklearn.utils import shuffle

In [12]:
dataset = pd.read_csv("./UJIIndoorLoc/children_13/sorted/00_sorted.csv")
dataset["REF"] = pd.factorize(dataset["REF"])[0].astype(int)#将标签映射到顺序数字上
labels = dataset.REF.values
features = dataset.drop(columns=['TIMESTAMP','PHONEID','USERID','RELATIVEPOSITION',
                                'SPACEID','BUILDINGID','FLOOR','LATITUDE','LONGITUDE',
                                'BF','REF']).values
print(features,labels)
# a = [np.where(labels==0)][0] #返回列表(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,17, 18, 19], dtype=int64),)
# a
# path = "./UJIIndoorLoc/children_13/sorted/00_sorted.csv"
# train_df = pd.read_csv(path,header=0)
# print(train_df.shape)
# a = train_df.mean()
# for i in train_df.columns[:520]:
#     if (a[i]<-109):
#         del train_df[i]
# print(train_df.shape)
# train_df["REF"] = pd.factorize(train_df["REF"])[0].astype(int)#将标签映射到顺序数字上
# labels = train_df.REF.values
# features = train_df.drop(columns=['TIMESTAMP','PHONEID','USERID','RELATIVEPOSITION',
#                                 'SPACEID','BUILDINGID','FLOOR','LATITUDE','LONGITUDE',
#                                 'BF','REF']).values
# features,labels,features.shape

[[-110 -110 -110 ... -110 -110 -110]
 [-110 -110 -110 ... -110 -110 -110]
 [-110 -110 -110 ... -110 -110 -110]
 ...
 [-110 -110 -110 ... -110 -110 -110]
 [-110 -110 -110 ... -110 -110 -110]
 [-110 -110 -110 ... -110 -110 -110]] [ 0  0  0 ... 53 53 53]


In [13]:
X_train, X_test, Y_train, Y_test = train_test_split(features, 
                                                    labels, 
                                                    test_size=0.3,
                                                    random_state= 150,
                                                    #random_state：可以理解为随机数种子，主要是为了复现结果而设置
                                                    stratify=labels)
X_train,Y_train = shuffle(X_train, Y_train)

In [14]:
import time
for k in range(10):
    s_time = time.time()
    knn = neighbors.KNeighborsClassifier(n_neighbors = k+1)
    knn.fit(X_train,Y_train)
#   t_label = knn.predict(X_test)
    e_time = time.time()
    acc = knn.score(X_test,Y_test) 
    print('k = %d  the accurancy is: %.4f, and it cost %.4f s'  % (k+1, acc, e_time-s_time))

k = 1  the accurancy is: 0.7264, and it cost 0.0010 s
k = 2  the accurancy is: 0.7013, and it cost 0.0010 s
k = 3  the accurancy is: 0.7138, and it cost 0.0000 s
k = 4  the accurancy is: 0.7044, and it cost 0.0000 s
k = 5  the accurancy is: 0.7075, and it cost 0.0010 s
k = 6  the accurancy is: 0.7170, and it cost 0.0011 s
k = 7  the accurancy is: 0.7170, and it cost 0.0000 s
k = 8  the accurancy is: 0.6981, and it cost 0.0010 s
k = 9  the accurancy is: 0.6855, and it cost 0.0020 s
k = 10  the accurancy is: 0.6792, and it cost 0.0000 s
